output_dir: result
#property: logP
random_seed: 3
token: model/tokens.pkl

model_json: model/model.tf25.json
model_weight: model/model.tf25.best.ckpt.h5

reward_setting: 
  reward_module: reward.logP_reward
  reward_class: LogP_reward